err_t (*detruire)(struct entite_s ** ent);
void (*lire)(struct entite_s * ent);
char * nom, *description;
pos_t pos;
int w,h,w_hitbox,h_hitbox, nbTextures;
SDL_Texture ** textures;
chunk_t * chunk;
salle_t * salle;
int vitesse_x,vitesse_y;
booleen_t en_vie;